# Photoacoustic Water Vapor Analyzer Configuration Example
# --------------------------------------------------------
# This YAML file configures the rust-photoacoustic application.
# YAML is a text based structured file format @see https://en.wikipedia.org/wiki/YAML
# It must pass validation against config.schema.json (see docs for schema details).
# To view the schema, run: `rust-photoacoustic ---show-config-schema`
#
# =========================
# HOW TO GENERATE SECRETS AND CERTIFICATES
# =========================
#
# --- Generate RSA keypair for RS256 JWT signing ---
# POSIX (Linux/macOS):
#   openssl genpkey -algorithm RSA -out private.key -pkeyopt rsa_keygen_bits:2048
#   openssl rsa -pubout -in private.key -out pub.key
#   cat private.key | base64 -w0 > private.key.b64
#   cat pub.key | base64 -w0 > pub.key.b64
# Windows (using Git Bash or WSL):
#   Same as above, or use OpenSSL for Windows (https://slproweb.com/products/Win32OpenSSL.html)
#   Use 'base64 -w0' or 'certutil -encode' (then remove header/footer lines)
#
# --- Generate a PEM certificate for HTTPS (self-signed) ---
# POSIX:
#   openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=localhost"
#   base64 -w0 cert.pem > cert.txt
#   base64 -w0 key.pem > key.txt
# Windows:
#   Use OpenSSL for Windows as above, or use PowerShell:
#   New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "cert:\LocalMachine\My"
#   # Export as PEM using certmgr or OpenSSL
#
# --- Generate a password hash for a user ---
# POSIX:
#   openssl passwd -5 mypassword | base64 -w0
# Windows:
#   Use Git Bash or WSL for the above, or use Python:
#   python -c "import crypt,base64; print(base64.b64encode(crypt.crypt('mypassword', crypt.mksalt(crypt.METHOD_SHA512)).encode()).decode())"
#
# --- Validate this YAML against the JSON schema ---
# 1. Convert YAML to JSON (e.g. https://www.json2yaml.com/ or https://yaml-online-parser.appspot.com/)
# 2. Use an online JSON schema validator (e.g. https://www.jsonschemavalidator.net/)
#    - Upload your converted JSON
#    - Upload config.schema.json from the repository
#    - Validate and check for errors
#
# =========================
# Visualization server settings
# =========================
visualization:
  # TCP port for the web server (default: 8080)
  port: 8080
  # IP address to bind the server (use 0.0.0.0 for all interfaces)
  address: 127.0.0.1
  # Server name/version string (for HTTP headers and logs)
  name: LaserSmartApiServer/0.1.0

  # Secret key for signing session cookies (keep this private!)
  # Generate securely: `openssl rand -base64 32`
  session_secret: 6wcVSUhxt1+YPEondChFXtesCL1boh57gqHv2gnEH7U=

  # SSL certificate and key (Base64-encoded PEM, optional for HTTPS)
  # To enable HTTPS, provide both cert and key fields below.
  # Generate and encode with:
  #   cat rust-photoacoustic.local.pem | base64 -w0 > cert.txt
  #   cat rust-photoacoustic.local.key | base64 -w0 > key.txt
  cert: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBS3FZcWszcVAwTkQrelJDeTdIMjZrUHVuQmpMTEpFNQp4Z0p5VzBQZm8wb3pUelV0Tk1DZFRHZzB5a3hFSjA5NXVEUXpGYWZxME5FcTBWeG40MjJZWXRzQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUJWUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQVQ4d2dnRTdBZ0VBQWtFQXFwaXFUZW8vUTBQN05FTEwKc2ZicVErNmNHTXNza1RuR0FuSmJROStqU2pOUE5TMDB3SjFNYURUS1RFUW5UM200TkRNVnArclEwU3JSWEdmagpiWmhpMndJREFRQUJBa0JzVWlXSTlaMFh5L21jZEhFOFhnamYrNGs0SVFINmNKR3ZDZ2V6TURSUnJ2cHRjM0YwCnVETEN5K21kQnBPOCs2b2FvcE9wN3hIa053OU42U2FPMGZhWkFpRUE0cjArbEpOQ3FZaGdSdTNIb2xKT0dRMkUKcnVTdHUrZStRM2pxVnN3U29zVUNJUURBbktLalFJdEZONnpxdHpPK1lnanNudFNOeG1iKzdlSnRsY2JLa0FMSgpId0loQUlRL1h3M25xbjBaaHhZM3dEWGtEWnM5TUVPV0srTXFjdVlGMDZEV25KUUZBaUJUb3pDVVJ6Q3lxOHh3ClY0RW1pSmRyZUVUQUU0a2g1ZFpPMDV6dzFMd0E3UUloQU1maU5ULzVXYzY1YzhGNWR6MFRvQjQ1aTVZYVRNYnoKbkNwQWpGQm5kN0E0Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  # JWT authentication secrets:
  # HMAC secret for HS256 JWT signing (used for API authentication)
  hmac_secret: my-super-secret-jwt-key-for-photoacoustic-app

  # RSA keys for RS256 JWT signing (Base64-encoded PEM, used for API authentication)
  # Generate with the `rs256keygen` utility or OpenSSL.
  # These are optional unless you want RS256 support.
  rs256_private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUdyQWdFQUFpRUFyd0FZcXAvdGVvaUE4N2FWQStJTjQ1U1RvMTdMUVZPbGRUT3FJeHhQeElNQ0F3RUFBUUlnCldRVlpodUpYOGE4aXVkYzFNb1o1dldYcmxwdFlEUTQ3RXUwa2pNVVA2T0VDRVFEUjEyN0RsZWNKNU80V3B2VEcKdnQ1YkFoRUExWDZ4ZVVzUXpISkZTYlV4eXZEYStRSVJBS2Z1b05ZbHdTQko5Y0JySExseFJzRUNFUURCcTBOZApqNTMyaUxhWURablV5amNwQWhCSG9CU1JSTS9ESVA5dWE1MDhYMEtOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  rs256_public_key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1DZ0NJUUN2QUJpcW4rMTZpSUR6dHBVRDRnM2psSk9qWHN0QlU2VjFNNm9qSEUvRWd3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K

  # Compression
  # Enable or disable compression at the rocket server level.
  # This is useful for reducing bandwidth usage, especially for large data transfers.
  compression: true
  
# =========================
# Modbus TCP server settings
# =========================
modbus:
  # TCP port for Modbus server
  port: 1502
  # IP address to bind Modbus server
  address: "127.0.0.1"
  # Enable or disable Modbus server
  enabled: false

# =========================
# Photoacoustic acquisition settings
# =========================
photoacoustic:
  # Input source: specify either input_device (e.g. alsa:0) or input_file (wav file)
  #input_device: alsa:0
  input_file: input.wav

  # Excitation frequency in Hz for the laser
  frequency: 2000.0

  # Bandwidth of the band-pass filter (Hz)
  bandwidth: 100.0

  # Analyzer window size (samples)
  # The length is seconds of this window can be calculated as:
  #   frame_size / sampling_rate
  # For example, with a frame_size of 4096 and sampling_rate of 44100:
  #   4096 / 44100 = 0.0929 seconds (approximately 93 ms)
  frame_size: 4096

  # Sampling rate in Hz
  sampling_rate: 44100

  # Number of spectra to average for noise reduction
  averages: 10

  # Simulated photoacoustic source configuration
  # When present, enables simulation mode with comprehensive physics modeling
  # Comment out or set to null to use real hardware sources
  simulated_source:
    # Source type: 'mock' for simple MockSource or 'universal' for full physics simulation
    # - mock: Lightweight simulation with correlation-based signal generation
    # - universal: Complete physics simulation with Helmholtz resonance, gas flow, thermal drift
    source_type: "mock"
    
    # Inter-channel correlation coefficient [-1.0, 1.0] for dual-microphone configuration
    # Used by 'mock' source type for simple correlation-based generation
    correlation: 0.8
    
    # Background noise amplitude [0.0, 1.0] - thermal and electronic noise
    background_noise_amplitude: 0.1
    
    # Helmholtz resonance frequency [Hz] - cell acoustic resonance
    resonance_frequency: 2100.0
    
    # Laser modulation depth [0.0, 1.0] - photoacoustic signal strength
    laser_modulation_depth: 0.8
    
    # Base photoacoustic signal amplitude [0.0, 1.0]
    signal_amplitude: 0.5
    
    # Phase opposition between microphones [degrees] - differential configuration
    phase_opposition_degrees: 180.0
    
    # Temperature drift effect factor [0.0, 0.1] - thermal stability
    temperature_drift_factor: 0.01
    
    # Gas flow noise factor [0.0, 1.0] - turbulent flow effects
    gas_flow_noise_factor: 0.05
    
    # Signal-to-noise ratio factor [0.1, 100.0] - measurement quality
    snr_factor: 10.0
    
    # Laser modulation mode: 'amplitude' (continuous) or 'pulsed' (discrete)
    modulation_mode: "amplitude"
    
    # Pulse width [seconds] - for pulsed modulation mode
    pulse_width_seconds: 0.05
    
    # Pulse frequency [Hz] - for pulsed modulation mode
    pulse_frequency_hz: 20.0

  # Alternative: Universal physics simulation configuration
  # Uncomment and modify the source_type to "universal" to use comprehensive physics modeling
  # simulated_source:
  #   source_type: "universal"
  #   correlation: 0.8
  #   background_noise_amplitude: 0.1
  #   resonance_frequency: 2100.0
  #   laser_modulation_depth: 0.9
  #   signal_amplitude: 0.7
  #   phase_opposition_degrees: 175.0
  #   temperature_drift_factor: 0.02
  #   gas_flow_noise_factor: 0.3
  #   snr_factor: 25.0
  #   modulation_mode: "amplitude"
  #   pulse_width_seconds: 0.005
  #   pulse_frequency_hz: 100.0

  # Record consumer settings
  # If enabled, the stream data will be consumed by the record consumer
  record_consumer: true

# =========================
# Access control and user management
# =========================
access:
  iss: LaserSmartServer # Issuer for JWT tokens
  duration: 86400 # Optional duration in seconds of the issued tokens minimum 3600, maximum 31536000
  users:
    # List of users with hashed passwords and permissions
    # Passwords are hashed (e.g. with openssl passwd -5) and base64-encoded
    - user: administrator
      pass: JDUkcVc2NUtlSTVwb2ZRMC5VTCRmTnl2Vjh4MTJQMnBvcXlGa2htUnNRRWhLRFV3LzIuUVpseDc1UEFxeWdECg== # password: 'password'
      permissions:
        - "read:api"
        - "write:api"
        - "admin:api"
      # Optional user metadata
      email: administrator@example.org
      name: Administrator User
    - user: reader
      pass: JDUkRmp3NUJRLlM1alZkOXVkciRma0E3eG9PYnhiL1Uxam1UeU05VjhzcDVPb1F3VzBSN1gzRW9pMjN0ZVVBCg== # password: '123445678'
      permissions:
        - "read:api"
      email: reader@example.org
  clients:
    # OAuth2/OpenID Connect clients allowed to use the API
    - client_id: LaserSmartClient
      default_scope: "openid profile email read:api write:api"
      allowed_callbacks:
        - "http://localhost:8080/client/"
        - "https://localhost:8080/client/"

  # =========================
  # OAuth2/OpenID Connect client configuration (for web client)
  # =========================
  generix:
    issuer: LaserSmartServer # Issuer for the OAuth2/OpenID Connect server, must match the access.iss value
    provider: generix # Only 'generix' is supported
    api_base_url: https://localhost:8080 # Base URL of the API server
    authority: https://localhost:8080 # Authority URL for OAuth2/OpenID Connect
    client_id: LaserSmartClient # OAuth2/OpenID Connect client ID
    scope: "openid email profile read:api write:api" # Scopes requested by the client
    redirect_uri: https://localhost:8080/client/ # Redirect URI after authentication
    audience: Client # Audience claim in JWT tokens
    token_issuer: https://localhost:8080 # Token issuer base URL
    jwks_endpoint: https://localhost:8080/.well-known/jwks.json # JWKS endpoint for public keys
    domain: localhost # Domain for the client application

# =========================
# Signal processing configuration
# =========================
processing:
  enabled: true
  result_buffer_size: 1000
  default_graph:
    id: default
    nodes:
    - id: input
      node_type: input
      parameters: null
    # Record original audio
    - id: "original_recorder"
      node_type: "record"
      parameters:
        record_file: "./recordings/original.wav"
        max_size: 1024
        auto_delete: false
        total_limit: 5120  # Maximum 5MB total for all recordings
    
    # Apply differential processing
    - id: "differential_detection"
      node_type: "differential"
      parameters: null

    - id: "streaming_post_differential"
      node_type: "streaming"
      parameters: null
    
    - id: bandpass_filter
      node_type: filter
      parameters:
        type: bandpass
        center_frequency: 2000.0  # Center at 2 kHz
        bandwidth: 200.0          # 200 Hz bandwidth (1900-2100 Hz passband)
        order: 2                  # optional order second-order (-12dB/octave)  (must be even)
                                  # for first-order use a combination of lowpass and highpass filters

    # Apply gain adjustment (+3 dB amplification)
    - id: "gain_amplifier"
      node_type: "gain"
      parameters:
        value: 3.0  # +3 dB gain (approximately 1.41x amplification)

    - id: "streaming_bandpass_filter"
      node_type: "streaming"
      parameters: null

    # Record processed audio
    - id: "processed_recorder"
      node_type: "record"
      parameters:
        record_file: "./recordings/processed.wav"
        max_size: 1024
        auto_delete: false
        total_limit: 10240  # Maximum 10MB total for all recordings

    # Graph connections
    connections:
    - from: input
      to: original_recorder
    - from: original_recorder
      to: differential_detection
    - from: differential_detection
      to: streaming_post_differential
    - from: streaming_post_differential
      to: bandpass_filter
    - from: bandpass_filter
      to: streaming_bandpass_filter
    - from: streaming_bandpass_filter
      to: processed_recorder
    - from: streaming_bandpass_filter
      to: gain_amplifier
    - from: gain_amplifier
      to: processed_recorder
      
  performance:
    max_processing_time_us: 10000
    enable_stats: true
    stats_interval_ms: 1000